import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "../../context/Authcontext";
import { ThemeProvider } from "../../context/ThemeContext";
import NavBar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/footer";
import {CartProvider }from "../../context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <CartProvider>
              <NavBar />
              {children}
              <Footer />
            </CartProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
